export enum ErrorCodes {
    USER_NOT_FOUND = "USER_NOT_FOUND",
    EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS",
    INCORRECT_PASSWORD_OF_USER = "INCORRECT_PASSWORD_OF_USER",
    NOT_VALID_TOKEN = "NOT_VALID_TOKEN",
    RESOURCE_ALREADY_EXISTS = "RESOURCE_ALREDY_EXISTS",
    MALFORMED_REQUEST = "MALFORMED_REQUEST",
    NOT_FOUND = "NOT_FOUND",
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
    RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND"
}
